# Generated by Django 2.1.2 on 2018-10-03 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CatApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catpicture',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='catpicture',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
