# Generated by Django 2.1.2 on 2018-10-11 05:51

import CatApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatApp', '0002_auto_20181003_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='catpicture',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=CatApp.models.get_image_path),
        ),
    ]
